# -------------------------------------------------- #
# -----------      [RIV CONFIG FILE]       --------- #
# --------------  made  by  Architetto  ------------ #
# -------------------------------------------------- #


RESPAWN:
  w: 'world'
  x: 100
  y: 66
  z: -179

DOORS_RADIUS_DETECTOR : 10

#in secondi
OPEN_DOORS_DELAY : 10
CLOSE_DOORS_DELAY : 30

#----------------------------------------------------#

ANTI_CAMPER_TOGGLE : true

AC_DELAY : 300
AC_PERIOD : 120
AC_DAMAGE : 1 #1 is half heart

REWARD_PLAYER_ON_TOP : true
#in secondi
REWARD_PERIOD : 60
REWARD_MIN_PLAYERS : 1
MAX_REWARD_AMOUNT : 10
#todo REWARD_ITEMS_LIST

#---- NOT IMPLEMENTED - WIP - EXPERIMENTAL MODE ----#

TOGGLE_POSITIVE_POTION_EFFECT : true
TOGGLE_NEGATIVE_POTION_EFFECT : true

