#WIP
SPES_TP_LOCATION:
#------------------------------------------------#

#-------------NON ANCORA UTILIZZATI--------------#

TOGGLE_POSITIVE_POTION_EFFECT : true
TOGGLE_NEGATIVE_POTION_EFFECT : true

#------------------------------------------------#
