# -------------------------------------------------- #
# -----------      [RIV CONFIG FILE]       --------- #
# --------------  made  by  Architetto  ------------ #
# -------------------------------------------------- #


RESPAWN:
  w: 'world'
  x: 100
  y: 66
  z: -179

DOORS_RADIUS_DETECTOR : 10

#seconds
OPEN_DOORS_DELAY : 10
CLOSE_DOORS_DELAY : 30

#----------------------------------------------------#

ANTI_CAMPER_TOGGLE : true

AC_MIN_PLAYER_ACTIVATION : 3
AC_DELAY : 60
AC_PERIOD : 30
AC_DAMAGE : 1 #Positive int value beetwen 1 and 20 (1 is half heart)

REWARD_PLAYER_ON_TOP : true
REWARD_PERIOD : 60
REWARD_MIN_PLAYERS : 1
MAX_REWARD_AMOUNT : 10

#---------------- SNOWBALL SETTINGS ----------------#

SNOWBALL_DOES_DAMAGE : true
SNOWBALL_DAMAGE : 0.2

SNOWBALL_DOES_KNOCKBACK : true
SNOWBALL_KNOCKBACK_POWER : 10

#---- NOT IMPLEMENTED - WIP - EXPERIMENTAL MODE ----#

#ITEM_NAME, WEIGHT, MAX_AMOUNT
LIST_ITEMS_REWARD:
  - 'SNOWBALL,3,5'
  - 'LEATHER_LEGGINGS,3,1'
  - 'LEATHER_BOOTS,3,1'
  - 'LEATHER_HELMET,4,1'
  - 'LEATHER_CHESTPLATE,2,1'
  - 'GOLDEN_APPLE,1,1'
  - 'MILK_BUCKET,2,1'
  - 'BAKED_POTATO,4,5'
  - 'FISHING_ROD,1,1'
  - 'TOTEM_OF_UNDYING,1,1'


TOGGLE_POSITIVE_POTION_EFFECT : true
TOGGLE_NEGATIVE_POTION_EFFECT : true

