# -------------------------------------------------- #
# -----------      [RIV CONFIG FILE]       --------- #
# --------------  made  by  Architetto  ------------ #
# -------------------------------------------------- #


RESPAWN:
  w: 'world'
  x: 100
  y: 66
  z: -179

DOORS_RADIUS_DETECTOR : 10

#set true if other plugin handle that
ALLOW_BREAK_BLOCK : true
ALLOW_PLACE_BLOCK : true
ALLOW_INTERACTION : true

#in seconds
OPEN_DOORS_DELAY : 5
CLOSE_DOORS_DELAY : 15

#--------------    FOOD SETTINGS     --------------#

MIN_FOOD_LEVEL : 10 #0 - 20
RESET_FOOD_LEVEL : 18 #0 - 20

#-------------  ANTI CAMPER SETTINGS   -------------#

ANTI_CAMPER_TOGGLE : true
AC_DELAY : 60
AC_DAMAGE_PERIOD : 2
AC_DAMAGE : 2
AC_MIN_REDLINE_DIFFERENCE : 5
AC_REDLINE_GROW_PERIOD : 30
RED_LINE_GROW_VALUE : 2

#---------- REWARD PLAYER SYSTEM SETTINGS ----------#

REWARD_PLAYER_ON_TOP : true
REWARD_PERIOD : 20
REWARD_MIN_PLAYERS : 1

#---------------- SNOWBALL SETTINGS ----------------#

SNOWBALL_DOES_DAMAGE : true
SNOWBALL_DAMAGE : 0.1

SNOWBALL_DOES_KNOCKBACK : true
SNOWBALL_KNOCKBACK_POWER : 1

#---------------- MINIGAMES SETTINGS ----------------#

DEATH_RACE_PERIOD : 120

#----------------    OTHER SETTINGS   ---------------#

#ITEM_NAME, MAX_AMOUNT
START_LOADOUT:
  - 'COOKED_PORKCHOP,15'

#ITEM_NAME, WEIGHT, MAX_AMOUNT
LIST_ITEMS_REWARD:
  - 'SNOWBALL,3,10'
  - 'LEATHER_LEGGINGS,3,1'
  - 'LEATHER_BOOTS,3,1'
  - 'LEATHER_HELMET,3,1'
  - 'LEATHER_CHESTPLATE,2,1'
  - 'GOLDEN_APPLE,1.1,1'
  - 'MILK_BUCKET,1.5,1'
  - 'BAKED_POTATO,5,5'
  - 'FISHING_ROD,0.6,1'
  - 'ENCHANTED_GOLDEN_APPLE,0.5,1'
  - 'TOTEM_OF_UNDYING,0.1,1'






