name: Rivevent
version: ${project.version}
main: me.architetto.rivevent.RIVevent
api-version: 1.16
authors: [Architetto]
description: Automatizza l'evento 'Resta In Vetta'
commands:
  rivevent:
    description: Automatizza l'evento 'Resta in Vetta'.

permissions:
  rivevent.admin:
    description: description
    default: op
    children:
      rivevent.create : true
      rivevent.delete : true
      rivevent.superuser : true
      rivevent.reload : true

  rivevent.superuser:
    description: description
    default: false
    children:
      rivevent.init : true
      rivevent.restart : true
      rivevent.minigame : true
      rivevent.list : true
      rivevent.setup : true
      rivevent.start : true
      rivevent.stop : true
      rivevent.user : true
      rivevent.eventinfo : true

  rivevent.user:
    description: description
    default: true
    children:
      rivevent.join : true
      rivevent.leave : true
      rivevent.spectate : true