# -------------------------------------------------- #
# -----------      [RIV CONFIG FILE]       --------- #
# --------------  made  by  Architetto  ------------ #
# -------------------------------------------------- #

RESPAWN_POINT:

FOOD_LEVEL: 12

ANTI_CAMPER_START_DELAY: 15
ANTI_CAMPER_DAMAGE_PERIOD: 1
ANTI_CAMPER_DAMAGE: 2
ANTI_CAMPER_DAMAGE_FINAL_BOOST: 2
ANTI_CAMPER_GROW_PERIOD: 10
ANTI_CAMPER_GROW_VALUE: 3
ANTI_CAMPER_RL_DIF: 5

RED_LINE_ANIMATION_RADIUS: 15

REWARD_PERIOD: 20

SNOWBALL_KNOCKBACK_POWER: 10
SNOWBALL_DAMAGE: 0.1

ENABLE_TARGET_BLOCK: true
TARGET_BLOCK_COOLDOWN: 30

DEATH_RACE_PERIOD: 30
CURSE_PERIOD: 60

START_LOADOUT:
  - 'COOKED_PORKCHOP,15'

LIST_ITEMS_REWARD:
  - 'SNOWBALL,3,16'
  - 'LEATHER_LEGGINGS,3,1'
  - 'LEATHER_BOOTS,3,1'
  - 'LEATHER_HELMET,3,1'
  - 'LEATHER_CHESTPLATE,2,1'
  - 'GOLDEN_APPLE,1.1,1'
  - 'ENDER_PEARL,1.1,2'
  - 'MILK_BUCKET,1.5,1'
  - 'TRIDENT,0.2,1'
  - 'COOKED_PORKCHOP,5,16'
  - 'FISHING_ROD,0.4,1'
  - 'ENCHANTED_GOLDEN_APPLE,0.01,1'
  - 'TOTEM_OF_UNDYING,0.1,1'

LIST_UNIQUE_ITEMS:
  - 'LEATHER_BOOTS'
  - 'LEATHER_LEGGINGS'
  - 'LEATHER_CHESTPLATE'
  - 'LEATHER_HELMET'
  - 'FISHING_ROD'
  - 'TOTEM_OF_UNDYING'
  - 'ENCHANTED_GOLDEN_APPLE'







