##################################################################
## ------------------------------------------------------------ ##
##          ███████╗██╗    ██╗    ██████╗ ██╗██╗   ██╗          ##
##          ██╔════╝██║    ██║    ██╔══██╗██║██║   ██║          ##
##          █████╗  ██║ █╗ ██║    ██████╔╝██║██║   ██║          ##
##          ██╔══╝  ██║███╗██║    ██╔══██╗██║╚██╗ ██╔╝          ##
##          ██║     ╚███╔███╔╝    ██║  ██║██║ ╚████╔╝           ##
##          ╚═╝      ╚══╝╚══╝     ╚═╝  ╚═╝╚═╝  ╚═══╝            ##
##                      Made by: Architetto                     ##
##     SOURCE CODE: https://github.com/ForgottenWorld/FWRiv     ##
## ------------------------------------------------------------ ##
##################################################################

#ITEM LOADOUT: {Material material, int amount}
START_LOADOUT:
  - 'COOKED_PORKCHOP,15'
  - 'HONEYCOMB,10'

NO_DAMAGE_PERIOD: 30

REWARD_SYSTEM:
  DELAY: 30
  PERIOD: 45
  ALLRANDOM: true

ANTI_CAMPER_SYSTEM:
  DELAY: 120
  GROW_PERIOD: 15
  GROW_VALUE: 5
  START_DAMAGE: 2
  FINAL_DAMAGE: 5
  MAX_HEIGHT_DIF: 5

#ITEM REWARD: {Material .., double weight, int maxAmount, boolean unique}
#POTION REWARD: {PotionEffetcType .., double weight, int minTickDuration, int maxTickDuration, int amplifier, DyeColor dyeColor}
#EFFECT REWARD: {PotionEffetcType .., double weight, int minTickDuration, int maxTickDuration, int amplifier}

# [Material LIST--->] https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# [PotionEffectType LIST--->] https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
# [DyeColor LIST--->] https://hub.spigotmc.org/javadocs/spigot/org/bukkit/DyeColor.html

# SPECIAL ITEMS LIST: ENDER PEARL, SNOWBALL, TOTEM OF UNDYING, FISHING ROD, LEAD (pickpoket), SHEARS (armor shred)

TOWER_REWARDS:
  EFFECTS:
    - 'REGENERATION,1.5,100,300,2'
    - 'WEAKNESS,1.5,200,400,1'
    - 'INCREASE_DAMAGE,1.5,200,300,1'
    - 'ABSORPTION,1.5,200,300,1'
    - 'DAMAGE_RESISTANCE,3,400,600,2'
  ITEMS:
    - 'SNOWBALL,13.5,10,false'
    - 'LEATHER_LEGGINGS,5.5,1,true'
    - 'LEATHER_BOOTS,5.5,1,true'
    - 'LEATHER_HELMET,5.5,1,true'
    - 'LEATHER_CHESTPLATE,8,1,true'
    - 'GOLDEN_APPLE,3.5,1,false'
    - 'ENDER_PEARL,3,1,true'
    - 'MILK_BUCKET,3,1,true'
    - 'LEAD,1.9,1,true'
    - 'COOKED_PORKCHOP,10.5,16,false'
    - 'FISHING_ROD,7.5,1,true'
    - 'ENCHANTED_GOLDEN_APPLE,0.5,1,true'
    - 'TOTEM_OF_UNDYING,1.4,1,true'
    - 'HONEYCOMB,5,10,false'
    - 'FIREWORK_ROCKET,5,7,false'
  POTIONS:
    - 'REGENERATION,2,100,300,2,LIGHT_BLUE'
    - 'SLOW,2,200,400,2,LIGHT_GRAY'
    - 'BLINDNESS,4,100,400,1,GRAY'
    - 'SLOW_FALLING,3.5,600,1200,1,PINK'


TARGETBLOCK_REWARDS:
  EFFECTS:
    - 'REGENERATION,2,100,600,1'
    - 'POISON,2,200,400,1'
    - 'HEALTH_BOOST,1.5,600,1100,2'
    - 'HUNGER,1.5,200,600,2'
  ITEMS:
    - 'SNOWBALL,10,10,false'
    - 'LEATHER_LEGGINGS,3.5,1,true'
    - 'LEATHER_BOOTS,3,1,true'
    - 'LEATHER_HELMET,3,1,true'
    - 'ENDER_PEARL,1.8,1,true'
    - 'SHEARS,1.8,1,true'
    - 'LEAD,1.3,1,true'
    - 'MILK_BUCKET,2.5,1,true'
    - 'COOKED_PORKCHOP,8.5,14,false'
    - 'FISHING_ROD,5,1,true'
    - 'HONEYCOMB,6.5,10,false'
    - 'FIREWORK_ROCKET,5,5,false'
    - 'LEAD,1.5,1,true'
  POTIONS:
    - 'WITHER,2.5,100,500,1,BLACK'
    - 'CONFUSION,2.5,200,500,2,BROWN'
    - 'BLINDNESS,2.5,400,600,1,GRAY'
    - 'POISON,2.4,100,300,1,GREEN'


TARGET_BLOCK:
  COOLDOWN: 30
  EXPLOSION_POWER: 1.4

SNOWBALL:
  DAMAGE: 0.3
  KNOCKBACK: 1.2

FISHING_ROD:
  PULL_POWER: 3

HONEY_COMB:
  HEALTH: 2






